name: ci

on:
  push:
    tags:
      - "*"
    paths:
      - "Dockerfile"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}
        with:
          push: true
          tags: "$IMAGE_NAME:latest,$IMAGE_NAME:${{ github.ref_name }}"
